Lesson.create!([
  {title: "Windows 10: hardware", video_path: nil, activity_path: "https://www.dropbox.com/s/8j7dwmrdc2ttfqi/Aula%201%20-%20Hardware.pdf?dl=0"},
  {title: "Windows 10: sistema operacional, configurações e menu Iniciar", video_path: nil, activity_path: "https://www.dropbox.com/s/vu71mirag715k66/Aula%202%20-%20Sistema%20Operacional.pdf?dl=0"},
  {title: "Word: introdução e formatação de textos", video_path: "lBqZOjWE94g", activity_path: "https://www.dropbox.com/s/udz1epumdrc28oa/Aula%201%20-%20Formata%C3%A7%C3%A3o%20de%20textos.pdf?dl=0"},
  {title: "Word: formatação de parágrafos e correção ortográfica", video_path: "Vh8FpKurJVM", activity_path: "https://www.dropbox.com/s/a5xtp57vtqi1nsw/Aula%202%20-%20Formata%C3%A7%C3%A3o%20de%20par%C3%A1grafos.pdf?dl=0"},
  {title: "Word: formatação de páginas e colunas", video_path: "FUlFzO8hEsQ", activity_path: "https://www.dropbox.com/s/zfumsru7zljvgoy/Aula%203%20-%20Formata%C3%A7%C3%A3o%20de%20p%C3%A1ginas%20e%20colunas.pdf?dl=0"},
  {title: "Word: design, temas e estilos", video_path: "jcWYOB3obiw", activity_path: "https://www.dropbox.com/s/8u31mxsioo8ghlf/Aula%204%20-%20Design%20e%20temas.pdf?dl=0"},
  {title: "Word: marcadores e numeradores", video_path: "OQm0Za_uONQ", activity_path: "https://www.dropbox.com/s/86jeno5ogid1vrq/Aula%205%20-%20Marcadores%20e%20numeradores.pdf?dl=0"},
  {title: "Word: cabeçalhos, rodapés e números de páginas", video_path: "CGqnKhWHYZQ", activity_path: "https://www.dropbox.com/s/4osfx8s71iv8egg/Aula%207%20Ex%201%20-%20Cabe%C3%A7alhos%20e%20rodap%C3%A9s.pdf?dl=0"},
  {title: "Word: ortografia/gramática, localizar/substituir, impressão e PDF", video_path: nil, activity_path: nil},
  {title: "Word: AVALIAÇÃO FORMATIVA", video_path: nil, activity_path: "https://www.dropbox.com/s/io6t43tmrjmzatf/Aula%208%20-%20Avalia%C3%A7%C3%A3o%20Formativa.pdf?dl=0"},
  {title: "Word: sumário, referências bibliográficas e notas de rodapé", video_path: "TyA-_aa0cbA", activity_path: "https://www.dropbox.com/s/o130o5jvjqo22r1/Aula%209%20-%20Sum%C3%A1rio%20e%20refer%C3%AAncias.pdf?dl=0"},
  {title: "Word: imagens e formatação de imagens", video_path: "-Q4Rz_jYLTg", activity_path: "https://www.dropbox.com/s/h5ztm2s8c7qj6bz/Aula%2010%20-%20Imagens.pdf?dl=0"},
  {title: "Word: formas, elementos SmartArt, caixas de texto e gráficos", video_path: "cTi4W3Ut6RY", activity_path: "https://www.dropbox.com/s/zhns9aqgjx8kg4g/Aula%2011%20-%20Formas%20e%20SmartArt.pdf?dl=0"},
  {title: "Word: símbolos, equações, capitular e hifenização", video_path: "SNhJxF4lF_A", activity_path: "https://www.dropbox.com/s/4204x30ysc9u7nb/Aula%2012%20-%20Equa%C3%A7%C3%B5es%20S%C3%ADmbolos%20Capitular.pdf?dl=0"},
  {title: "Word: hiperlinks e mala direta", video_path: "IobKwb1gaes", activity_path: nil},
  {title: "Word: tabelas", video_path: "tzRB3q6ZnxM", activity_path: "https://www.dropbox.com/s/bfi1n7jqqhf83kt/Aula%2014%20-%20Tabelas.pdf?dl=0"},
  {title: "Word: PROVA FINAL SOMATIVA", video_path: nil, activity_path: nil},
  {title: "Excel: introdução ao Excel, linhas, colunas e formatação de texto", video_path: "XzIlvjn0XXw", activity_path: "https://www.dropbox.com/s/vwotyw3zwqtehmd/Aula%201%20-%20Introdu%C3%A7%C3%A3o%20ao%20Excel.pdf?dl=0"},
  {title: "Excel: planilhas, cálculos básicos e referências de células", video_path: "P5n6onw5FYo", activity_path: "https://www.dropbox.com/s/qj6vp3k9uml022a/Aula%202%20-%20Planilhas%20e%20refer%C3%AAncias.pdf?dl=0"},
  {title: "Excel: formatação de números, decimais, porcentagens e moeda", video_path: "PsEDXGzR15E", activity_path: "https://www.dropbox.com/s/3chnp9terpbsm7t/Aula%203%20-%20Formata%C3%A7%C3%A3o%20de%20n%C3%BAmeros.pdf?dl=0"},
  {title: "Excel: filtros, classificação e tabelas automáticas", video_path: "j6JFpU6QY3A", activity_path: nil},
  {title: "Excel: formatação condicional", video_path: "pJJcv9-f__0", activity_path: "https://www.dropbox.com/s/5hu2etibllxvb6i/Aula%205%20-%20Formata%C3%A7%C3%A3o%20condicional.pdf?dl=0"},
  {title: "Excel: validação de dados e testes de hipóteses", video_path: nil, activity_path: nil},
  {title: "Excel: AVALIAÇÃO FORMATIVA", video_path: nil, activity_path: "https://www.dropbox.com/s/7n0wg0zeudqrral/Aula%207%20-%20Avalia%C3%A7%C3%A3o%20formativa.pdf?dl=0"},
  {title: "Excel: introdução à funções", video_path: "7_5TjeHyRBQ", activity_path: "https://www.dropbox.com/s/lualg9wyeamkg4z/Aula%208%20-%20Fun%C3%A7%C3%B5es.pdf?dl=0"},
  {title: "Excel: funções matemáticas, estatísticas e funções compostas", video_path: "zVGj6lYnhpc", activity_path: "https://www.dropbox.com/s/c4xky3c0uausy5h/Aula%209%20-%20Fun%C3%A7%C3%B5es%20matem%C3%A1ticas%20e%20estat%C3%ADsticas.pdf?dl=0"},
  {title: "Excel: funções financeiras (PGTO, TAXA, VF/VP)", video_path: nil, activity_path: "https://www.dropbox.com/s/xsse96anmlg7f28/Aula%2010%20-%20Fun%C3%A7%C3%B5es%20financeiras.pdf?dl=0"},
  {title: "Excel: funções de busca (PROCV/PROCH)", video_path: "FjFViXyHJuI", activity_path: "https://www.dropbox.com/s/vqmfwnnfmm0ayr2/Aula%2011%20-%20Fun%C3%A7%C3%B5es%20de%20busca%20%28PROCV%29.pdf?dl=0"},
  {title: "Excel: funções lógicas e condicionais (SE)", video_path: "KbQcZ-g6dXU", activity_path: "https://www.dropbox.com/s/o98zbat5evo8iwb/Aula%2012%20-%20Fun%C3%A7%C3%B5es%20l%C3%B3gicas%20%28SE%29.pdf?dl=0"},
  {title: "Excel: funções lógicas e condicionais (E/OU)", video_path: "oelAT86GNWo", activity_path: "https://www.dropbox.com/s/3e5tk480e4p530a/Aula%2013%20-%20Fun%C3%A7%C3%B5es%20l%C3%B3gicas%20%28E%20OU%29.pdf?dl=0"},
  {title: "Excel: gráficos de pizza e colunas", video_path: "XlEq8wm5N2s", activity_path: "https://www.dropbox.com/s/fhbtig0p00x6ae5/Aula%2014%20-%20Gr%C3%A1ficos%20de%20pizza%20e%20colunas.pdf?dl=0"},
  {title: "Excel: gráficos de linha e dispersão", video_path: "S0vXOTu1F7s", activity_path: "https://www.dropbox.com/s/1zcvoy82eoo3x59/Aula%2015%20-%20Gr%C3%A1ficos%20de%20linha%20e%20dispers%C3%A3o.pdf?dl=0"},
  {title: "Excel: gráficos adicionais + minigráficos", video_path: nil, activity_path: nil},
  {title: "Excel: imagens, formas, SmartArt, símbolos e equações", video_path: nil, activity_path: "https://www.dropbox.com/s/nu8jsvxapi9g4eg/Aula%2017%20-%20Formas%20e%20SmartArt.pdf?dl=0"},
  {title: "Excel: PROVA FINAL SOMATIVA", video_path: nil, activity_path: nil},
  {title: "Microsoft Office: Outlook, OneDrive, OneNote", video_path: nil, activity_path: nil},
  {title: "PowerPoint: inserir slides, duplicar/mover slides, layout de slides", video_path: "rboU0m09Wsw", activity_path: "https://www.dropbox.com/s/urftjutj1k0toe1/Aula%201%20-%20Criando%20slides.pdf?dl=0"},
  {title: "PowerPoint: temas, cores e plano de fundos", video_path: "_dy3km09D5E", activity_path: "https://www.dropbox.com/s/6s0dkzxf45awjo9/Aula%202%20-%20Design%20e%20temas.pdf?dl=0"},
  {title: "PowerPoint: transições e animações", video_path: "5UvPWAn57q8", activity_path: "https://www.dropbox.com/s/ch2hj3zmyzts66g/Aula%203%20-%20Transi%C3%A7%C3%B5es%20e%20anima%C3%A7%C3%B5es.pdf?dl=0"},
  {title: "PowerPoint: apresentação e gravação de slides", video_path: "kkU1974EMdg", activity_path: "https://www.dropbox.com/s/qj0j4ifvoj2yzkk/Aula%204%20-%20Apresenta%C3%A7%C3%A3o%20e%20grava%C3%A7%C3%A3o%20de%20slides.pdf?dl=0"},
  {title: "PowerPoint: modos de exibição, corretor e tradutor", video_path: "IATLL0QxRGM", activity_path: "https://www.dropbox.com/s/zdrx2s5x44dc34t/Aula%205%20-%20Modos%20de%20exibi%C3%A7%C3%A3o.pdf?dl=0"},
  {title: "PowerPoint: gráficos e tabelas", video_path: nil, activity_path: nil},
  {title: "PowerPoint: áudio, vídeo e diagramas SmartArt", video_path: nil, activity_path: nil},
  {title: "PowerPoint: PROVA FINAL SOMATIVA", video_path: nil, activity_path: nil}
])
